### ISSUE TITLE
Character labels with invalid characters get invisibly eaten

### ISSUE THREAD

**Issue by SimonGreenhill** [dlce-eva/commonnexus#16]
When character labels have invalid characters e.g. "()", the label gets eaten. For example, in this nexus the two labels `burn(tr.)_3` and `claw(nail)_3`:

```shell
#NEXUS

BEGIN DATA;
    DIMENSIONS NTAX=3 NCHAR=3;
    FORMAT DATATYPE=STANDARD MISSING=? GAP=- SYMBOLS="01";
    CHARSTATELABELS
        1 hand_1,
        2 burn(tr.)_3,
        3 claw(nail)_3
        ;
MATRIX
A   001
B   000
C   000
;
END;
```

This has the side effect that data can be deleted invisibly e.g. this is what the resulting data matrix looks like, note that the third character has replaced the second:

```python
OrderedDict([
    ('A', OrderedDict([('hand_1', '0'), ('_3', '1')])), 
    ('B', OrderedDict([('hand_1', '0'), ('_3', '0')])), 
    ('C', OrderedDict([('hand_1', '0'), ('_3', '0')]))
])
```

commonnexus should probably emit a warning or an error in this case.

It would be nice to handle this better e.g. by converting to "burn_tr_3" or similar, and 
guard against overwriting of characters (it'd be better to have duplicate _3's than lose one).

**Comment by xrotwang** [comment]
Ok, what happens is that simply the last word token before a comma is read as label. Thus, two characters get a label `_3`, which leads to the values for the second character being overwritten by the third in the matrix.

**Comment by xrotwang** [comment]
You should have seen a warning about a duplicate charstatelabel, though.

**Comment by xrotwang** [comment]
Any kind of conversion would require some sort of config setting, which states what non-word tokens to allow/convert in charstatelabels, I think. So raising a `ValueError` here seems to be the best we can do.

**Comment by xrotwang** [comment]
> You should have seen a warning about a duplicate charstatelabel, though.

Just found another bug, where the warning about duplicate state labels wasn't emitted for the last label :)

**Comment by SimonGreenhill** [comment]
great, thanks!
